<?php

namespace backend\widgets;

use common\models\Author;
use common\models\Book;
use common\models\BookAuthor;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\db\Query;

class AuthorsBooksWidget extends \yii\base\Widget
{
    public $author;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(is_numeric($this->author)) {
            $this->author = Author::findOne($this->author);
        }

        if ($this->author === null) {
            $this->author = '';
        }
    }

    public function run()
    {
        if(!$this->author) {
            return '';
        }

        //$this->author = Author::findOne($this->author);

        $dataProvider = new ArrayDataProvider([
            'allModels' => $this->author->books
        ]);


        return $this->render('books', ['dataProvider' => $dataProvider]);

    }
}