<?php

namespace backend\components;

use common\models\Author;
use common\models\Book;
use common\models\BookAuthor;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\db\Query;

class AuthorsBooksWidget extends \yii\base\Widget
{
    public $author_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if ($this->author_id === null) {
            $author_id = 1;
        }
    }

    public function run()
    {
        $id = 1;
        if(Yii::$app->request->post()) {
            $id = intval(Yii::$app->request->post()["Author"]["id"]);
        }

        $author = Author::findOne($id);

        $dataProvider = new ArrayDataProvider([
            'allModels' => $author->books
        ]);

        return $this->render('books', ['dataProvider' => $dataProvider]);

    }
}